apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: sugarizer-vs-{{required "schoolShortName not defined" .Values.schoolShortName}}
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
spec:
  host: {{required "hostName not defined" .Values.hostName}}
  upstreams:
  - name: web
    service: sugarizer-service-server-{{required "schoolShortName not defined" .Values.schoolShortName}}
    subselector:
     school: {{required "schoolShortName not defined" .Values.schoolShortName}}
     app: http
    port: 8080
  - name: ws
    service: sugarizer-service-ws-{{required "schoolShortName not defined" .Values.schoolShortName}}
    subselector:
     school: {{required "schoolShortName not defined" .Values.schoolShortName}}
     app: http
    port: 8039
  routes:
  - path: /
    matches:
    - conditions:
      - header: Upgrade
        value: websocket
      action:
        pass: ws
    action:
      pass: web