apiVersion: v1
kind: Secret
metadata:
  name: https-mirror-secret-{{required "schoolShortName not defined" .Values.schoolShortName}}
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: '{{required "sspNamespace not defined" .Values.sspNamespace}}/https-secret-{{required "sspNamespace not defined" .Values.sspNamespace}}'
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sugarizer-service-db-np-{{required "schoolShortName not defined" .Values.schoolShortName}}
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      school: {{required "schoolShortName not defined" .Values.schoolShortName}}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          school: {{required "schoolShortName not defined" .Values.schoolShortName}}

---

apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: sugarizer-vs-{{required "schoolShortName not defined" .Values.schoolShortName}}
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
spec:
  tls:
    secret: https-mirror-secret-{{required "schoolShortName not defined" .Values.schoolShortName}}
  host: {{required "hostName not defined" .Values.hostName}}
  upstreams:
  - name: web
    service: sugarizer-service-server-{{required "schoolShortName not defined" .Values.schoolShortName}}
    port: 80
  - name: ws
    service: sugarizer-service-ws-{{required "schoolShortName not defined" .Values.schoolShortName}}
    port: 8039
  routes:
  - path: /
    matches:
    - conditions:
      - header: Upgrade
        value: websocket
      action:
        pass: ws
    action:
      pass: web
