apiVersion: v1
kind: Service
metadata:
  name: sugarizer-service-{{required "schoolShortName not defined" .Values.schoolShortName}}
  namespace: sugarizer-{{required "schoolShortName not defined" .Values.schoolShortName}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{required "schoolShortName not defined" .Values.schoolShortName}}.sugarizer.tools.
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: websocket
    port: 8039
    targetPort: 8039
    protocol: TCP
  selector:
    school: {{required "schoolShortName not defined" .Values.schoolShortName}}
    app: http
